name: foodon
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  equatable: ^2.0.0
  http: ^0.13.2
  get_it: ^6.1.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  built_value: ^8.0.5
  built_collection: ^5.0.0
  data_connection_checker: ^0.3.4
  persistent_bottom_nav_bar: ^4.0.2
  dartz: ^0.9.2
  another_flushbar: ^1.10.22

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  built_value_generator: ^8.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons_png/logo_png.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/food_images/
    - assets/images/icons/
    - assets/images/icons_png/
    - assets/images/profile_icons/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Black-FD-UI.ttf
        - asset: assets/fonts/Vazir-Bold-FD-UI.ttf
        - asset: assets/fonts/Vazir-Light-FD-UI.ttf
        - asset: assets/fonts/Vazir-Medium-FD-UI.ttf
        - asset: assets/fonts/Vazir-Regular-FD-UI.ttf
        - asset: assets/fonts/Vazir-Thin-FD-UI.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
